import postgres, { type Sql } from "postgres";

type QueryResult<T> = { results: T[]; success: true; meta: { changes: number; last_row_id?: number } };
type CountedRows<T> = T[] & { count?: number };

let client: Sql | undefined;
let configuredUrl: string | undefined;

function connection(explicitUrl?: string): Sql {
  const url = explicitUrl ?? configuredUrl ?? process.env.SUPABASE_DB_URL;
  if (!url) {
    throw new Error("SUPABASE_DB_URL is not configured. Set it to the Supabase transaction-pooler connection string.");
  }
  configuredUrl = url;
  client ??= postgres(url, {
    max: 5,
    prepare: false,
    ssl: "require",
    idle_timeout: 20,
    connect_timeout: 15,
  });
  return client;
}

function placeholders(source: string): string {
  let output = "";
  let index = 0;
  let quote: "'" | '"' | "`" | null = null;
  for (let i = 0; i < source.length; i += 1) {
    const character = source[i];
    if (quote) {
      output += quote === "`" && character === "`" ? '"' : character;
      if (character === quote && source[i - 1] !== "\\") quote = null;
      continue;
    }
    if (character === "'" || character === '"' || character === "`") {
      quote = character;
      output += character === "`" ? '"' : character;
    } else if (character === "?") {
      index += 1;
      output += `$${index}`;
    } else {
      output += character;
    }
  }
  return output;
}

function postgresSql(source: string): string {
  let query = source.trim().replace(/;$/, "");
  const pragma = query.match(/^PRAGMA\s+table_info\(([^)]+)\)$/i);
  if (pragma) {
    return `SELECT column_name AS name FROM information_schema.columns WHERE table_schema='public' AND table_name='${pragma[1].replace(/["'`]/g, "")}' ORDER BY ordinal_position`;
  }
  query = query
    .replace(/INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT/gi, "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    .replace(/INSERT\s+OR\s+IGNORE\s+INTO/gi, "INSERT INTO")
    .replace(/date\('now'\)/gi, "CURRENT_DATE::text")
    .replace(/datetime\('now'\s*,\s*'-(\d+) days'\)/gi, "(CURRENT_TIMESTAMP - interval '$1 days')::text")
    .replace(/DEFAULT\s+CURRENT_TIMESTAMP/gi, "DEFAULT (CURRENT_TIMESTAMP::text)")
    .replace(/=\s*CURRENT_TIMESTAMP\b/gi, "= CURRENT_TIMESTAMP::text");
  const ignored = /INSERT\s+OR\s+IGNORE\s+INTO/i.test(source);
  if (ignored && !/ON\s+CONFLICT/i.test(query)) query += " ON CONFLICT DO NOTHING";
  return placeholders(query);
}

class PreparedStatement {
  private parameters: unknown[] = [];

  constructor(private readonly source: string) {}

  bind(...parameters: unknown[]) {
    this.parameters = parameters;
    return this;
  }

  private async execute<T>(executor: Sql = connection(), returnId = false): Promise<T[]> {
    let query = postgresSql(this.source);
    if (returnId && /^INSERT\s+INTO/i.test(query) && !/\bRETURNING\b/i.test(query)) query += " RETURNING id";
    return (await executor.unsafe(query, this.parameters as never[])) as T[];
  }

  async all<T>(): Promise<QueryResult<T>> {
    const rows = (await this.execute<T>()) as CountedRows<T>;
    return { results: [...rows], success: true, meta: { changes: rows.count ?? rows.length } };
  }

  async first<T>(): Promise<T | null> {
    const rows = await this.execute<T>();
    return rows[0] ?? null;
  }

  async run(): Promise<QueryResult<unknown>> {
    const rows = (await this.execute<{ id?: number }>(connection(), true)) as CountedRows<{ id?: number }>;
    const lastId = rows[0]?.id;
    return {
      results: [...rows],
      success: true,
      meta: { changes: rows.count ?? rows.length, ...(lastId == null ? {} : { last_row_id: Number(lastId) }) },
    };
  }

  async executeWith(executor: Sql): Promise<QueryResult<unknown>> {
    let query = postgresSql(this.source);
    if (/^INSERT\s+INTO/i.test(query) && !/\bRETURNING\b/i.test(query)) query += " RETURNING id";
    const rows = (await executor.unsafe(query, this.parameters as never[])) as CountedRows<{ id?: number }>;
    const lastId = rows[0]?.id;
    return {
      results: [...rows],
      success: true,
      meta: { changes: rows.count ?? rows.length, ...(lastId == null ? {} : { last_row_id: Number(lastId) }) },
    };
  }
}

export type Database = ReturnType<typeof getDb>;

export function getDb(url?: string) {
  if (url) configuredUrl = url;
  return {
    prepare(query: string) {
      return new PreparedStatement(query);
    },
    async batch(statements: PreparedStatement[]) {
      return connection().begin(async (transaction) => {
        const results: QueryResult<unknown>[] = [];
        for (const statement of statements) results.push(await statement.executeWith(transaction as Sql));
        return results;
      });
    },
  };
}
