-- Generated from drizzle/meta/0018_snapshot.json for Supabase Postgres.

-- Text dates and integer booleans are preserved for a lossless D1 import.

CREATE TABLE IF NOT EXISTS public."appointments" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reference" text NOT NULL,
  "name" text NOT NULL,
  "email" text NOT NULL,
  "phone" text NOT NULL,
  "service" text NOT NULL,
  "consultation_mode" text NOT NULL,
  "preferred_date" text NOT NULL,
  "preferred_time" text NOT NULL,
  "project_type" text NOT NULL DEFAULT '',
  "message" text NOT NULL DEFAULT '',
  "status" text NOT NULL DEFAULT 'pending',
  "payment_status" text NOT NULL DEFAULT 'not-required',
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE UNIQUE INDEX IF NOT EXISTS "appointments_reference_unique" ON public."appointments" ("reference");

ALTER TABLE public."appointments" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."appointments" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."audit_logs" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "actor_email" text NOT NULL,
  "action" text NOT NULL,
  "entity_type" text NOT NULL,
  "entity_id" text NOT NULL DEFAULT '',
  "details_json" text NOT NULL DEFAULT '{}',
  "ip_address" text NOT NULL DEFAULT '',
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

ALTER TABLE public."audit_logs" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."audit_logs" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."branches" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "city" text NOT NULL,
  "address" text NOT NULL,
  "phone" text NOT NULL DEFAULT '',
  "email" text NOT NULL DEFAULT '',
  "map_url" text NOT NULL DEFAULT '',
  "status" text NOT NULL DEFAULT 'active',
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

ALTER TABLE public."branches" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."branches" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."certificates" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reference" text NOT NULL,
  "student_name" text NOT NULL,
  "student_email" text NOT NULL,
  "course_title" text NOT NULL,
  "issued_date" text NOT NULL,
  "status" text NOT NULL DEFAULT 'issued',
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE UNIQUE INDEX IF NOT EXISTS "certificates_reference_unique" ON public."certificates" ("reference");

ALTER TABLE public."certificates" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."certificates" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."client_files" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reference" text NOT NULL,
  "customer_email" text NOT NULL,
  "file_name" text NOT NULL,
  "object_key" text NOT NULL,
  "content_type" text NOT NULL,
  "size" bigint NOT NULL,
  "category" text NOT NULL DEFAULT 'Project file',
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE UNIQUE INDEX IF NOT EXISTS "client_files_reference_unique" ON public."client_files" ("reference");

CREATE UNIQUE INDEX IF NOT EXISTS "client_files_object_key_unique" ON public."client_files" ("object_key");

ALTER TABLE public."client_files" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."client_files" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."client_reports" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reference" text NOT NULL,
  "customer_email" text NOT NULL,
  "title" text NOT NULL,
  "report_type" text NOT NULL,
  "summary" text NOT NULL,
  "findings" text NOT NULL DEFAULT '',
  "recommendations" text NOT NULL DEFAULT '',
  "status" text NOT NULL DEFAULT 'draft',
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE UNIQUE INDEX IF NOT EXISTS "client_reports_reference_unique" ON public."client_reports" ("reference");

ALTER TABLE public."client_reports" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."client_reports" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."cms_pages" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "slug" text NOT NULL,
  "status" text NOT NULL DEFAULT 'draft',
  "excerpt" text NOT NULL DEFAULT '',
  "content" text NOT NULL DEFAULT '',
  "seo_title" text NOT NULL DEFAULT '',
  "seo_description" text NOT NULL DEFAULT '',
  "author_email" text NOT NULL,
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
  "updated_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE UNIQUE INDEX IF NOT EXISTS "cms_pages_slug_unique" ON public."cms_pages" ("slug");

ALTER TABLE public."cms_pages" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."cms_pages" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."consultant_projects" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reference" text NOT NULL,
  "owner_email" text NOT NULL,
  "project_name" text NOT NULL,
  "client_name" text NOT NULL,
  "property_type" text NOT NULL DEFAULT 'Residence',
  "address" text NOT NULL DEFAULT '',
  "city" text NOT NULL DEFAULT '',
  "facing" text NOT NULL DEFAULT 'North',
  "compass_rotation" bigint NOT NULL DEFAULT 0,
  "floor_plan_key" text NOT NULL DEFAULT '',
  "floor_plan_name" text NOT NULL DEFAULT '',
  "score" bigint NOT NULL DEFAULT 0,
  "findings_json" text NOT NULL DEFAULT '[]',
  "notes" text NOT NULL DEFAULT '',
  "status" text NOT NULL DEFAULT 'draft',
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
  "updated_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE UNIQUE INDEX IF NOT EXISTS "consultant_projects_reference_unique" ON public."consultant_projects" ("reference");

ALTER TABLE public."consultant_projects" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."consultant_projects" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."consultant_vastu_reports" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reference" text NOT NULL,
  "project_id" bigint NOT NULL,
  "owner_email" text NOT NULL,
  "client_email" text NOT NULL DEFAULT '',
  "title" text NOT NULL,
  "executive_summary" text NOT NULL DEFAULT '',
  "findings_json" text NOT NULL DEFAULT '[]',
  "remedies_json" text NOT NULL DEFAULT '[]',
  "conclusion" text NOT NULL DEFAULT '',
  "prepared_by" text NOT NULL DEFAULT '',
  "status" text NOT NULL DEFAULT 'draft',
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
  "updated_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE UNIQUE INDEX IF NOT EXISTS "consultant_vastu_reports_reference_unique" ON public."consultant_vastu_reports" ("reference");

ALTER TABLE public."consultant_vastu_reports" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."consultant_vastu_reports" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."courses" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "slug" text NOT NULL,
  "category" text NOT NULL,
  "level" text NOT NULL DEFAULT 'Beginner',
  "mode" text NOT NULL DEFAULT 'Recorded',
  "duration" text NOT NULL DEFAULT '',
  "description" text NOT NULL DEFAULT '',
  "price" bigint NOT NULL DEFAULT 0,
  "lessons" bigint NOT NULL DEFAULT 0,
  "status" text NOT NULL DEFAULT 'published',
  "image_url" text NOT NULL DEFAULT '',
  "instructor" text NOT NULL DEFAULT 'Attri Academy Faculty',
  "certificate" bigint NOT NULL DEFAULT 1,
  "show_in_shop" bigint NOT NULL DEFAULT 1,
  "meta_title" text NOT NULL DEFAULT '',
  "meta_keywords" text NOT NULL DEFAULT '',
  "meta_description" text NOT NULL DEFAULT '',
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE UNIQUE INDEX IF NOT EXISTS "courses_slug_unique" ON public."courses" ("slug");

ALTER TABLE public."courses" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."courses" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."customer_profiles" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" text NOT NULL,
  "full_name" text NOT NULL,
  "phone" text NOT NULL DEFAULT '',
  "company" text NOT NULL DEFAULT '',
  "address" text NOT NULL DEFAULT '',
  "city" text NOT NULL DEFAULT '',
  "state" text NOT NULL DEFAULT '',
  "pincode" text NOT NULL DEFAULT '',
  "gstin" text NOT NULL DEFAULT '',
  "status" text NOT NULL DEFAULT 'active',
  "account_type" text NOT NULL DEFAULT '',
  "registration_completed" bigint NOT NULL DEFAULT 0,
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
  "updated_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE UNIQUE INDEX IF NOT EXISTS "customer_profiles_email_unique" ON public."customer_profiles" ("email");

ALTER TABLE public."customer_profiles" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."customer_profiles" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."enrollments" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reference" text NOT NULL,
  "course_id" bigint NOT NULL,
  "student_name" text NOT NULL,
  "email" text NOT NULL,
  "phone" text NOT NULL,
  "experience" text NOT NULL DEFAULT '',
  "status" text NOT NULL DEFAULT 'pending',
  "payment_status" text NOT NULL DEFAULT 'pending',
  "progress" bigint NOT NULL DEFAULT 0,
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE UNIQUE INDEX IF NOT EXISTS "enrollments_reference_unique" ON public."enrollments" ("reference");

ALTER TABLE public."enrollments" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."enrollments" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."faqs" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "question" text NOT NULL,
  "answer" text NOT NULL,
  "category" text NOT NULL DEFAULT 'General',
  "sort_order" bigint NOT NULL DEFAULT 0,
  "status" text NOT NULL DEFAULT 'published',
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

ALTER TABLE public."faqs" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."faqs" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."invoices" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "number" text NOT NULL,
  "customer_name" text NOT NULL,
  "customer_email" text NOT NULL,
  "description" text NOT NULL,
  "amount" bigint NOT NULL,
  "tax_rate" bigint NOT NULL DEFAULT 0,
  "status" text NOT NULL DEFAULT 'issued',
  "due_date" text NOT NULL,
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE UNIQUE INDEX IF NOT EXISTS "invoices_number_unique" ON public."invoices" ("number");

ALTER TABLE public."invoices" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."invoices" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."leads" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "email" text NOT NULL DEFAULT '',
  "phone" text NOT NULL DEFAULT '',
  "service" text NOT NULL DEFAULT '',
  "status" text NOT NULL DEFAULT 'new',
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

ALTER TABLE public."leads" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."leads" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."notification_reads" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notification_id" bigint NOT NULL,
  "user_email" text NOT NULL,
  "read_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

ALTER TABLE public."notification_reads" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."notification_reads" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."notifications" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "recipient_email" text NOT NULL,
  "channel" text NOT NULL DEFAULT 'email',
  "subject" text NOT NULL,
  "message" text NOT NULL,
  "status" text NOT NULL DEFAULT 'queued',
  "scheduled_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
  "sent_at" text,
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

ALTER TABLE public."notifications" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."notifications" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."order_events" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint NOT NULL,
  "status" text NOT NULL,
  "note" text NOT NULL DEFAULT '',
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

ALTER TABLE public."order_events" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."order_events" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."orders" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reference" text NOT NULL,
  "customer_name" text NOT NULL,
  "email" text NOT NULL,
  "phone" text NOT NULL,
  "address" text NOT NULL,
  "city" text NOT NULL,
  "state" text NOT NULL,
  "pincode" text NOT NULL,
  "items_json" text NOT NULL,
  "subtotal" bigint NOT NULL,
  "shipping_amount" bigint NOT NULL DEFAULT 0,
  "total" bigint NOT NULL DEFAULT 0,
  "payment_method" text NOT NULL DEFAULT 'pay-after-confirmation',
  "status" text NOT NULL DEFAULT 'pending',
  "payment_status" text NOT NULL DEFAULT 'pending',
  "tracking_number" text NOT NULL DEFAULT '',
  "admin_notes" text NOT NULL DEFAULT '',
  "updated_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE UNIQUE INDEX IF NOT EXISTS "orders_reference_unique" ON public."orders" ("reference");

ALTER TABLE public."orders" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."orders" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."payment_records" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reference" text NOT NULL,
  "customer_name" text NOT NULL,
  "customer_email" text NOT NULL,
  "purpose" text NOT NULL,
  "gateway" text NOT NULL,
  "transaction_id" text NOT NULL DEFAULT '',
  "amount" bigint NOT NULL,
  "status" text NOT NULL DEFAULT 'pending',
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE UNIQUE INDEX IF NOT EXISTS "payment_records_reference_unique" ON public."payment_records" ("reference");

ALTER TABLE public."payment_records" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."payment_records" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."portal_notifications" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "message" text NOT NULL,
  "audience" text NOT NULL DEFAULT 'all',
  "recipient_email" text NOT NULL DEFAULT '',
  "severity" text NOT NULL DEFAULT 'info',
  "action_url" text NOT NULL DEFAULT '',
  "status" text NOT NULL DEFAULT 'published',
  "expires_at" text NOT NULL DEFAULT '',
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

ALTER TABLE public."portal_notifications" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."portal_notifications" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."products" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "slug" text NOT NULL,
  "category" text NOT NULL,
  "description" text NOT NULL DEFAULT '',
  "price" bigint NOT NULL,
  "stock" bigint NOT NULL DEFAULT 0,
  "status" text NOT NULL DEFAULT 'active',
  "image_url" text NOT NULL DEFAULT '',
  "item_type" text NOT NULL DEFAULT 'physical',
  "delivery_mode" text NOT NULL DEFAULT 'Online',
  "special_price" bigint NOT NULL DEFAULT 0,
  "special_from" text NOT NULL DEFAULT '',
  "special_to" text NOT NULL DEFAULT '',
  "duration" text NOT NULL DEFAULT '',
  "classes" bigint NOT NULL DEFAULT 0,
  "sort_order" bigint NOT NULL DEFAULT 0,
  "meta_title" text NOT NULL DEFAULT '',
  "meta_keywords" text NOT NULL DEFAULT '',
  "meta_description" text NOT NULL DEFAULT '',
  "service_type" text NOT NULL DEFAULT '',
  "fulfillment_mode" text NOT NULL DEFAULT '',
  "sku" text NOT NULL DEFAULT '',
  "short_description" text NOT NULL DEFAULT '',
  "material" text NOT NULL DEFAULT '',
  "colour" text NOT NULL DEFAULT '',
  "dimensions" text NOT NULL DEFAULT '',
  "weight" text NOT NULL DEFAULT '',
  "placement" text NOT NULL DEFAULT '',
  "benefits" text NOT NULL DEFAULT '',
  "usage_instructions" text NOT NULL DEFAULT '',
  "care_instructions" text NOT NULL DEFAULT '',
  "gst_rate" bigint NOT NULL DEFAULT 18,
  "hsn_code" text NOT NULL DEFAULT '',
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE UNIQUE INDEX IF NOT EXISTS "products_slug_unique" ON public."products" ("slug");

ALTER TABLE public."products" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."products" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."project_milestones" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" bigint NOT NULL,
  "title" text NOT NULL,
  "description" text NOT NULL DEFAULT '',
  "due_date" text NOT NULL,
  "completion" bigint NOT NULL DEFAULT 0,
  "status" text NOT NULL DEFAULT 'pending',
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

ALTER TABLE public."project_milestones" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."project_milestones" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."projects" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "category" text NOT NULL,
  "location" text NOT NULL DEFAULT '',
  "status" text NOT NULL DEFAULT 'draft',
  "description" text NOT NULL DEFAULT '',
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

ALTER TABLE public."projects" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."projects" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."service_catalog" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "slug" text NOT NULL,
  "category" text NOT NULL,
  "summary" text NOT NULL DEFAULT '',
  "base_price" bigint NOT NULL DEFAULT 0,
  "duration" text NOT NULL DEFAULT '',
  "delivery_mode" text NOT NULL DEFAULT 'Online + On-site',
  "status" text NOT NULL DEFAULT 'active',
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE UNIQUE INDEX IF NOT EXISTS "service_catalog_slug_unique" ON public."service_catalog" ("slug");

ALTER TABLE public."service_catalog" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."service_catalog" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."site_settings" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "setting_key" text NOT NULL,
  "setting_value" text NOT NULL DEFAULT '',
  "value_type" text NOT NULL DEFAULT 'text',
  "is_public" bigint NOT NULL DEFAULT 0,
  "updated_by" text NOT NULL DEFAULT '',
  "updated_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE UNIQUE INDEX IF NOT EXISTS "site_settings_setting_key_unique" ON public."site_settings" ("setting_key");

ALTER TABLE public."site_settings" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."site_settings" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."staff_members" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" text NOT NULL,
  "full_name" text NOT NULL,
  "phone" text NOT NULL DEFAULT '',
  "role" text NOT NULL,
  "department" text NOT NULL,
  "permissions_json" text NOT NULL DEFAULT '[]',
  "status" text NOT NULL DEFAULT 'active',
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE UNIQUE INDEX IF NOT EXISTS "staff_members_email_unique" ON public."staff_members" ("email");

ALTER TABLE public."staff_members" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."staff_members" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."subscriptions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reference" text NOT NULL,
  "customer_email" text NOT NULL,
  "account_type" text NOT NULL,
  "plan_name" text NOT NULL,
  "billing_cycle" text NOT NULL DEFAULT 'monthly',
  "amount" bigint NOT NULL DEFAULT 0,
  "status" text NOT NULL DEFAULT 'pending',
  "starts_at" text NOT NULL DEFAULT '',
  "ends_at" text NOT NULL DEFAULT '',
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
  "updated_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE UNIQUE INDEX IF NOT EXISTS "subscriptions_reference_unique" ON public."subscriptions" ("reference");

ALTER TABLE public."subscriptions" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."subscriptions" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."support_tickets" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reference" text NOT NULL,
  "customer_email" text NOT NULL,
  "subject" text NOT NULL,
  "category" text NOT NULL,
  "message" text NOT NULL,
  "status" text NOT NULL DEFAULT 'open',
  "priority" text NOT NULL DEFAULT 'normal',
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE UNIQUE INDEX IF NOT EXISTS "support_tickets_reference_unique" ON public."support_tickets" ("reference");

ALTER TABLE public."support_tickets" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."support_tickets" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."testimonials" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_name" text NOT NULL,
  "designation" text NOT NULL DEFAULT '',
  "location" text NOT NULL DEFAULT '',
  "quote" text NOT NULL,
  "rating" bigint NOT NULL DEFAULT 5,
  "status" text NOT NULL DEFAULT 'pending',
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

ALTER TABLE public."testimonials" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."testimonials" FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public."workflow_tasks" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reference" text NOT NULL,
  "title" text NOT NULL,
  "assignee" text NOT NULL,
  "due_date" text NOT NULL,
  "priority" text NOT NULL DEFAULT 'normal',
  "status" text NOT NULL DEFAULT 'pending',
  "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE UNIQUE INDEX IF NOT EXISTS "workflow_tasks_reference_unique" ON public."workflow_tasks" ("reference");

ALTER TABLE public."workflow_tasks" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."workflow_tasks" FROM anon, authenticated;

CREATE UNIQUE INDEX IF NOT EXISTS notification_read_unique ON public.notification_reads (notification_id, user_email);

-- Server-side access uses the confidential SUPABASE_DB_URL connection; no Data API policies are granted.
